config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :videos
  resources :users


  get '/videos/:id/like' => 'videos#like'
  get '/videos/:id/dislike' => 'videos#dislike'

match 'login/', to: 'login#login_page', :via => [:post, :get]
match ':controller(/:action(:/id))', :via => [:post, :get]
  mount Sidekiq::Web => '/sidekiq'

  root 'videos#index'
end

app/models/post.rb
class Post < ActiveRecord::Base

   has_attached_file :video, styles: {
    :medium => {
      :geometry => "300x300",
      :format => 'mp4'
    },
    :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 10}
  }, :processors => [:transcoder]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  # Association declaration
  has_many :videos

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
:omniauthable, :omniauth_providers => [:facebook]

def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
    end


end

app/models/video.rb
class Video < ActiveRecord::Base
  # Association declaration
  belongs_to :user

  # Paperclip attachments declaration
  has_attached_file :video_file
  has_attached_file :mp4_file
  has_attached_file :webm_file
  has_attached_file :ogg_file
  # Styles declaration makes paperclip to use imagemagick to resize image to given size
  has_attached_file :thumbnail, styles: { medium_nr: "250x150!", thumb: "80x80" }

  # Paperclip requires to set attachment validators
  validates_attachment_content_type :video_file, content_type: /\Avideo/
  validates_attachment_content_type :mp4_file, content_type: /.*/
  validates_attachment_content_type :webm_file, content_type: /.*/
  validates_attachment_content_type :ogg_file, content_type: /.*/

  # We want video model always to have :video_file attachment
  validates_attachment_presence :video_file

  after_create :run_encoders
  # Publish video makes it available
  def publish!
    self.published = true
    save
  end

  # Increment likes counter
  def like!
    self.likes += 1
    save
  end

  # Decrease likes counter
  def dislike!
    self.likes -= 1
    save
  end

  # Checks if all formats are already encoded, the simplest way
  def all_formats_encoded?
    self.webm_file.path || self.mp4_file.path || self.ogg_file.path ? true : false
  end

  def run_encoders
  ThumbnailCutter.perform_async(self.id)
  Mp4VideoEncoder.perform_async(self.id)
  OgvVideoEncoder.perform_async(self.id)
  WebmVideoEncoder.perform_async(self.id)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_filter :check_user_is_active, except: [:login_page]

  before_filter :require_login
  before_filter :create_video


private

  def require_login
    unless current_user || controller_name == 'callbacks'
      #abort controller_name
      redirect_to controller: :login, action: :login_page
    end
  end

   def create_video
    @video = Video.new
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

layout 'qbe_frontend', :only => [:login_page]
skip_before_filter :require_login

  def login_page
    redirect_to controller: :videos, action: :index unless current_user.nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def index
  end

  def show
      @post=Post.find(params[:id])
  end

  def create
    @post = Post.new(permit_post)
      if @post.save
        flash[:success]
        redirect_to post_path(@post)
      else
        flash[:error]=@post.errors.full_messages
        redirect_to new_post_path
      end
  end

  private
    def permit_post
      params.permit(:video)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Checks if user is signed in before running controller, functionality provided by devise
  before_action :authenticate_user!

  before_action :set_user, only: [:show]
  before_action :set_current_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!

  # All published videos
  def index
    @videos = Video.where(published: 1)
  end

  def show
    if params[:id]
      @video = Video.find_by(id: params[:id])
    end
  end

  def new
    @video = Video.new
  end

  def edit
  end

  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to :back, notice: 'Video was successfully created.' }

      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # Likes video, increment likes count
  def like
    @video.like!
  end

  # Dislikes video, increment likes count
  def dislike
    @video.dislike!
  end

  private


  def video_params
    params.require(:video).permit(:video_file, :name, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppinionV1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'Appinion', root_url, class: 'navbar-brand'%>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#"></a>
                    </li>
                    <li>
                        <a href="#"></a>
                    </li>
                    <li>
                        <a href="#"></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="wrapper-body">
          <% flash.each do |a,b| %>
              <div class="alert alert-success"><%= b %></div>
          <% end %>
          <%= yield %>
    </div>
    <!-- /.wrapper-body -->
        <!-- Footer -->

<footer>
        <button type="button" id="choose-file-fake"onclick="chooseFile();"><i class="fa fa-video-camera" aria-hidden="true"></i></button>
            <%= simple_form_for @video, html: { multipart: true, class: 'upload-button' } do |f| %>
            <div style="height:0px;overflow:hidden">
                <%= f.input :video_file, as: :file%>
            </div>
            <%= f.hidden_field :user_id, :value => current_user.id %>
             <button type="button" id="upload-button-fake"onclick="uploadFile();" style="display:none"><i class="fa fa-cloud-upload fa-2x" aria-hidden="true"></i></button>
                <div style="height:0px;overflow:hidden">
                <%= f.button :submit, class: 'btn-primary', id:'upload-hidden-button', value: 'Upload Video'%>
                </div>
            <% end %>

     <script>
     //repalace the ugly default choose file button
       function chooseFile() {
          $("#video_video_file").click();
       }

       //replace the upload button
       function uploadFile() {
        //repalace the ugly default choose file button
          $("#upload-hidden-button").click();
       }


       //detect if a file has been chosen
       $('#video_video_file').change(function() {
        // If the upload field is empty, we'll hide te upload button,
        // Otherwise, let's show it.
        if($('#video_video_file').val() ==null ) {

        } else {
           $('#choose-file-fake').hide();
           $('#upload-button-fake').show();
        } // end if/else

    });
    </script>
</footer>



</body>

</html>

app/views/layouts/qbe_frontend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qbe</title>
    <link rel="import" href="/polymer_components/paper-input/paper-input.html">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>


      <meta name="description" content="Qbe es el nuevo linkedin pero repotenciado. Ahora los endorsements son mas realisticos y dicen mas de ti y tus amigos" />
    <meta name="viewport" content="width=device-width">
  </head>
<body class="home_body">
<div class="home">

     <div class="raya_login">
     </div><!--raya login-->
     <div class="login_box">
        LOG IN
     </div><!--login box-->
     <div class="raya_login">
     </div><!--raya login-->

     <%= link_to('<i class="fa fa-facebook-square fa-3x" aria-hidden="true"></i>'.html_safe, omniauth_authorize_path(:user, :facebook))  %>


     <!--<%= link_to(fa_stacked_icon "linkedin", class: "fa-3x")%>-->
     <div class="forabetteryou_box">
        FOR A BETTER YOU
     </div><!--for a better you-->
  </div><!--home-->
  </body><!-- body home -->
  </html>

app/views/layouts/test_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppV1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">

                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <% flash.each do |a,b| %>
              <div class="alert alert-success"><%= b %></div>
          <% end %>
              <%= yield %>

     </div>
   </div>
        <!-- Footer -->

        <footer>

            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

</body>

</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

<input type="file" capture="camera" accept="video/*" id="cameraInput" name="cameraInput">

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= form_for @post, html: {multipart: true} do |f| %>

 <%= f.file_field :video %>
 <%= f.submit %>
 <% end %>
<!--<input type="file" capture="camera" accept="video/*" id="cameraInput" name="cameraInput">-->

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/users/edit.haml
.container
  .row
    .col-md-6.col-sm-12
      %h2 Edit profile

      = simple_form_for @user do |f|
        = f.input :email
        = f.button :submit, class: 'btn-primary', value: 'Update Profile'

app/views/users/show.haml
.container
  .row
    .col-md-12
      %h2= @user.email
.container
  .row
    - @user.videos.each do |video|
      .col-md-3.thumb.video-thumb{ 'data-video-id'=> video.id }
        .likes
          %span.likes-count= video.likes
          %span.glyphicon.glyphicon-heart
        = link_to video, class: 'thumbnail' do
          = image_tag video.thumbnail.url(:medium_nr)

app/views/videos/index.html.erb
<div id="topic-of-the-day">Tell us about yourself...</div>
<span id="clear"></span>
<div class="separating-line"></div>
<%= link_to('Cerrar Sesión', destroy_user_session_path, :method => :delete) %>
<% @videos.each do |v| %>
<div class="index-row">
     <%=link_to v.user.first_name+" "+v.user.last_name, :controller => 'videos', :action => 'show', :id=> v.id %>
<div class="index-row-right-side">
  <i class="fa fa-eye" aria-hidden="true"></i>
</div>
</div>
<div class="separating-line"></div>
<% end %>

app/views/videos/new.haml
.container
  .row
    .col-md-6.col-sm-12
      %h2 Upload new video

      = simple_form_for @video, html: { multipart: true } do |f|
        = f.input :name
        = f.input :video_file, as: :file
        = f.button :submit, class: 'btn-primary', value: 'Upload Video'